from chfem.io import export_for_chfem, import_raw, import_vector_field_from_chfem, import_scalar_field_from_chfem
from chfem.compute_properties import compute_conductivity, compute_elasticity, compute_permeability

